SELECT 
    EXTRACT(YEAR FROM s.SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM s.SALES_DATE) AS MONTH,
    u.GENDER,
    COUNT(DISTINCT s.USER_ID) AS USERS
FROM 
    ONLINE_SALE s
JOIN 
    USER_INFO u ON s.USER_ID = u.USER_ID
WHERE 
    u.GENDER IS NOT NULL
GROUP BY 
    EXTRACT(YEAR FROM s.SALES_DATE),
    EXTRACT(MONTH FROM s.SALES_DATE),
    u.GENDER
ORDER BY 
    YEAR,
    MONTH,
    u.GENDER;
