SELECT user.USER_ID, user.NICKNAME, SUM(board.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER user
JOIN USED_GOODS_BOARD board ON user.USER_ID = board.WRITER_ID
WHERE board.STATUS = 'DONE'
GROUP BY user.USER_ID, user.NICKNAME
HAVING SUM(board.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;
